name: dikitis
description: project skripsi
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.8+8

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  awesome_notifications: ^0.7.5-dev.3
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  delayed_widget: ^1.1.2
  dotted_border: ^2.0.0+3
  double_back_to_close: ^2.0.0
  extended_image: ^8.1.1
  carousel_slider: ^4.2.1
  flutter_image_compress: ^2.0.4
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.6.0
  permission_handler: ^11.0.0
  pin_code_fields: ^8.0.1

  flutter_html_v3: ^3.0.6
  device_info_plus: ^9.0.3
  pdf_render: ^1.4.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

#  flutter_launcher_icons: ^0.9.3
#  rename: ^2.0.1


flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: false
  #flutter pub get
  #flutter pub run flutter_launcher_icons:main

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lotties/
    - assets/images/
    - assets/texts/license/
    - assets/texts/url/
    - assets/html/
    - assets/documents/

  fonts:
    - family: poppins_bold
      fonts:
        - asset: assets/fonts/poppins_bold.ttf
    - family: poppins_medium
      fonts:
        - asset: assets/fonts/poppins_medium.ttf
    - family: poppins_semi_bold
      fonts:
        - asset: assets/fonts/poppins_semi_bold.ttf
